task: nerf
exp_name: image_fit
scene: 'lego'
gpu_ids: [0]

# modules
train_dataset_module: projects.image_fit.synthetic
test_dataset_module: projects.image_fit.synthetic
network_module: projects.image_fit.network
loss_module: projects.image_fit.loss
evaluator_module: projects.image_fit.evaluator

# epoch
epoch_iter: 500
save_latest_epoch: 20
eval_epoch: 10
log_interval: 100

# task_args
task_args:
  N_pixels: 8192
  chunk_size: 16384

# network
network:
    W: 128
    D: 4
    uv_encoder:
        type: 'frequency'
        input_dim: 2
        freq: 10

# train_dataset
train_dataset:
  data_root: 'data/nerf_synthetic'
  split: 'train'
  view: 0
  input_ratio: 1.

# test_dataset
test_dataset:
  data_root: 'data/nerf_synthetic'
  split: 'test'
  view: 0
  input_ratio: 0.5

# train
train:
  batch_size: 1
  learning_rate: 5e-4
  weight_decay: 0.
  num_epoch: 20
  lr_scheduler:
    type: 'exponential'
    gamma: 0.1
    decay_epochs: 20
  num_workers: 4

# test
test:
  batch_size: 1